language: php

php:
  - 5.6

install: cp .env.example .env

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run
  - phpunit